### ISSUE TITLE
Pomme assumes that char is signed.

### ISSUE THREAD

**Issue by NoelJB** [jorio/Pomme#8]
Pomme defines `SInt8` as `typedef char SInt8;`, but `char` is either signed or unsigned as per the C Language Specification, and unsigned on aarch64 with gcc.  Change:

```C
PommeTypes.h:
- typedef char                            SignedByte;
- typedef char                            SInt8;
+ typedef signed char                     SignedByte; 
+ typedef signed char                     SInt8;
```

**Comment by NoelJB** [comment]
Yes, `int8_t` would be preferred.  But I noticed that you hadn't used standard definitions for any of them, so I kept with the simplest change.

**Comment by jorio** [comment]
Fixed as discussed in https://github.com/jorio/BillyFrontier/issues/5.
